import {
  DigestLayout, MustRead, Paper, KeyPoints, PaperLink,
  WorthReading, NotableItem, Observation,
} from '@/components/digest'
import { type Locale, locales } from '@/lib/i18n'
import type { Metadata } from 'next'

const content = {
  zh: {
    roleName: 'World Action Model 研究者',
    title: '统一离散世界—动作词表：从人类交互视频学习物理闭环',
    description: 'World Action Model 与具身智能世界模型研究日报',
    overview: [
      'PhysBrain 1.5 把语言、末端执行器动作与未来 RGB/深度/机器人掩码统一为离散 token，以同一自回归骨干和输出头训练',
      'ActionPiece 将未来 16 步末端轨迹编码为 32 个动作 token，近期动作历史则提供跨数据源控制约定的局部系统辨识信号',
      '约 3 万小时人类交互视频提供理解、动作与后续状态监督，但动作执行和未来预测目前主要是离线定性验证',
    ],
    papers: [
      {
        num: 1,
        tag: 'Joint WAM - Autoregressive · Unified-Discrete · Shared Representation',
        title: 'PhysBrain 1.5: From Vision-Language Models to Physical Foundation Models',
        keyPoints: [
          '在 Qwen3-VL 上扩展语言、动作和视觉词表，三类输出共享 token embedding、语言模型骨干与输出头，并通过带任务 loss mask 的 next-token prediction 联合优化',
          'ActionPiece 使用 512 项码本把每只手腕未来 16 步、每步 10 维的相对位姿与夹爪状态轨迹编码为 32 个离散 token；前一动作块可作为局部运动上下文以适应不同 embodiment 的坐标轴、尺度和频率',
          '未来物理状态由同一时间戳下空间对齐的 RGB、深度与机器人掩码组成；共享 VQ-VAE 将三种模态交错序列化为 770 个 token，再由同一自回归输出头生成',
          '物理预训练来自约 3 万小时人类交互视频，包含 3120 万动作样本和 2680 万未来状态样本；8B 模型在 28 个具身理解基准上的平均分为 72.5，但动作与未来预测仅报告轨迹困惑度及定性结果',
        ],
        description: 'PhysBrain 1.5 符合 Joint WAM - Autoregressive 的 unified-discrete 路线：动作与未来视觉状态不只是附接到同一系统，而是进入统一词表、共享骨干和输出头，并由同一种因果序列目标更新参数。它进一步把未来状态拆成 RGB、深度和机器人掩码，保留外观、几何与 embodiment 占据信息；动作历史则承担轻量的系统辨识，使统一动作码本能在未完全规范化的多源数据上工作。对 WAM 研究最重要的价值是展示了如何从大规模人类视频同时构造动作—后续观测监督，再用机器人与仿真数据适配。不过论文的动作生成与未来预测是按任务格式请求的共享模型能力，而非同一次 rollout 中显式交错生成；也未给出闭环真实机器人任务成功率，因此现阶段更应视为统一世界—动作预训练底座，而不是已经验证的闭环策略。',
        href: 'https://arxiv.org/abs/2609.14973v1',
      },
    ],
    worthReading: [],
    observation: '今日唯一达到强相关门槛的新作是 PhysBrain 1.5。它把 WAM 的统一边界推向“词表与输出头”：未来动作块和未来 RGB/深度/掩码均被离散化，并在同一自回归模型中学习。相比联合扩散路线，这种设计天然兼容 VLM 基础设施和人类视频规模化预训练，但长达 770 token 的未来状态序列也带来生成成本，且世界预测尚未用于在线选择动作。Hugging Face Daily Papers 收录了该论文；Awesome-WAM 最新 README 的 Joint WAM 与 Diffusion-based Generation 章节没有同期新增论文。arXiv API 经代理和直连重试均返回 HTTP 429，搜索覆盖降级；发布日期、摘要、架构、数据规模与评测边界已通过 arXiv v1 摘要页、HTML 全文和 PDF 文本交叉核验。',
  },
  en: {
    roleName: 'World Action Model Researcher',
    title: 'A Unified Discrete World–Action Vocabulary Learned from Human Interaction',
    description: 'Daily research digest for World Action Models and embodied intelligence',
    overview: [
      'PhysBrain 1.5 represents language, end-effector actions, and future RGB/depth/robot masks as discrete tokens trained with one autoregressive backbone and output head',
      'ActionPiece encodes the next 16 end-effector steps into 32 action tokens, while recent action history provides a local system-identification signal across control conventions',
      'Roughly 30,000 hours of human interaction video supply understanding, action, and subsequent-state supervision, although action and future prediction are evaluated mainly offline and qualitatively',
    ],
    papers: [
      {
        num: 1,
        tag: 'Joint WAM - Autoregressive · Unified-Discrete · Shared Representation',
        title: 'PhysBrain 1.5: From Vision-Language Models to Physical Foundation Models',
        keyPoints: [
          'Extends Qwen3-VL with language, action, and visual vocabularies whose outputs share the token embedding, language-model backbone, and output head, jointly optimized by next-token prediction with task-specific loss masks',
          'ActionPiece uses a 512-entry codebook to encode each wrist’s next 16 steps—10D relative pose and gripper state per step—as 32 discrete tokens; the preceding action chunk provides local motion context for source-specific axes, scales, and frequencies',
          'A future physical state combines spatially aligned RGB, depth, and robot masks at one timestamp; a shared VQ-VAE interleaves the three modalities into 770 tokens generated by the same autoregressive output head',
          'Physical pre-training uses about 30,000 hours of human interaction video, including 31.2M action and 26.8M future-state samples; the 8B model averages 72.5 over 28 embodied-understanding benchmarks, but action and future prediction receive only perplexity and qualitative evidence',
        ],
        description: 'PhysBrain 1.5 fits the unified-discrete branch of Joint WAM - Autoregressive: actions and future visual states are not merely attached to one system, but enter a unified vocabulary, backbone, and output head whose parameters are updated by the same causal sequence objective. Its future representation separates RGB appearance, depth geometry, and robot occupancy, while action history performs lightweight system identification so one action codebook can span incompletely canonicalized sources. Its main WAM contribution is a scalable recipe for deriving both motion and subsequent-state supervision from human video before adapting with robot and simulation data. However, action and future-state generation are task-formatted capabilities of a shared model rather than explicitly interleaved outputs within one rollout, and no closed-loop real-robot task success is reported. It is therefore best read as a unified world–action pre-training foundation rather than a validated closed-loop policy.',
        href: 'https://arxiv.org/abs/2609.14973v1',
      },
    ],
    worthReading: [],
    observation: 'PhysBrain 1.5 is today’s only new paper that clears the strong-relevance threshold. It pushes WAM unification down to the vocabulary and output head: future action chunks and future RGB/depth/masks are discretized and learned in one autoregressive model. Compared with joint diffusion, this design naturally reuses VLM infrastructure and scales to human-video pre-training, although a 770-token future-state sequence is costly and world prediction is not yet used online to select actions. Hugging Face Daily Papers featured the paper. The latest Awesome-WAM README has no contemporaneous addition in its Joint WAM or Diffusion-based Generation sections. The arXiv API returned HTTP 429 after proxied and direct retries, so search coverage was degraded; the publication date, abstract, architecture, data scale, and evaluation boundary were cross-checked against the arXiv v1 abstract, full HTML, and PDF text.',
  },
}

export function generateStaticParams() {
  return locales.map(locale => ({ locale }))
}

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> {
  const { locale } = await params
  const c = content[locale]
  return {
    title: c.title,
    description: c.description,
    alternates: {
      languages: {
        'zh-CN': '/zh/daily/world-action-model/2026-09-15',
        en: '/en/daily/world-action-model/2026-09-15',
      },
    },
  }
}

export default async function Page({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params
  const c = content[locale]

  return (
    <DigestLayout locale={locale} date="2026-09-15" roleId="world-action-model" roleName={c.roleName} title={c.title} overview={c.overview}>
      <MustRead>
        {c.papers.map(paper => (
          <Paper key={paper.num} num={paper.num} tag={paper.tag} title={paper.title}>
            <KeyPoints points={paper.keyPoints} />
            <p className="text-[#2C2C24] leading-relaxed">{paper.description}</p>
            <PaperLink href={paper.href} title={paper.title} />
          </Paper>
        ))}
      </MustRead>
      <WorthReading>
        {c.worthReading.map((item: { num: number; title: string; tag: string; href: string; description: string }) => (
          <NotableItem key={item.num} num={item.num} title={item.title} tag={item.tag} href={item.href}>{item.description}</NotableItem>
        ))}
      </WorthReading>
      <Observation><p>{c.observation}</p></Observation>
    </DigestLayout>
  )
}
